template = ""
rev_id = 335
template_sha = "656172fb5ca68a68ee8547c7bc0cd1ce3f605fd7"

[replacements]
__GLOTTOLOG_ID__ = "gunw1252"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-gup"
__UND2C__ = "gup"
__UNDEFINED__ = "Gunwinggu"
__UND__ = "gup"
