template = ""
rev_id = 322
template_sha = "eb14866dc080346b46def6f27a66b1b5eca59898"

[replacements]
__GLOTTOLOG_ID__ = "gunw1252"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-gup"
__UND2C__ = "gup"
__UNDEFINED__ = "Gunwinggu"
__UND__ = "gup"
