template = ""
rev_id = 323
template_sha = "dfd6613f16d25eef74b592360a48496624ab327d"

[replacements]
__GLOTTOLOG_ID__ = "gunw1252"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-gup"
__UND2C__ = "gup"
__UNDEFINED__ = "Gunwinggu"
__UND__ = "gup"
